spring:
  application:
    name: ${SERVICE_NAME}
  config:
    import: "consul:"
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORt}
      discovery:
        instance-id: ${spring.application.name}:${random.uuid}
        hostname: ${DISCOVERY_HOSTNAME}
      config:
        enabled: true
        defaultContext: ${CONSUL_KV_DEFAULT}
        format: YAML
        watch:
          enabled: true
server:
  port: ${PORT}

keycloak:
  secret: ${SSO_SECRET}
  admin_user: ${SSO_USERNAME}
  admin_password: ${SSO_PASSWORD}
  admin_realm: ${SSO_REALM}