---
  al_image: "ghcr.io/kronbars-esports/tournaments-account-linker:latest"
  al_service_name: "AL"
  al_port: "5001"
  al_pg_port: "5432"
  al_pg_host: "{{pg_host}}"
  al_pg_db: "postgres"
  al_pg_user: "{{postgresql_admin_user}}"
  al_pg_password: "{{postgresql_admin_password}}"
  al_container_name: "account-linking"