---
  cc_image: "ghcr.io/kronbars-esports/tournaments-competition-core:latest"
  cc_service_name: "CC"
  cc_port: "5200"
  cc_pg_port: "5432"
  cc_pg_host: "{{pg_host}}"
  cc_pg_db: "postgres"
  cc_pg_user: "{{postgresql_admin_user}}"
  cc_pg_password: "{{postgresql_admin_password}}"
  cc_container_name: "mm"