---
  auth_image: "ghcr.io/kronbars-esports/tournaments-auth:latest"
  auth_service_name: "AUTH"
  auth_port: "5000"
  auth_pg_port: "5432"
  auth_pg_host: "{{pg_host}}"
  auth_pg_db: "postgres"
  auth_pg_user: "{{postgresql_admin_user}}"
  auth_pg_password: "{{postgresql_admin_password}}"
  auth_secret: "{{app_secret}}"
  auth_container_name: "auth"