---
  consul_image: "hashicorp/consul:latest"
  consul_container_name: "consul"
  consul_datacenter: "dc1"
  consul_dns_port: "8600"
  consul_api_port: "8500"
  consul_bootstrap_expect: "1"
  consul_node_name: "server-1"
  consul_ui_enabled: true
  consul_volume: "consul-data"