---
  ds_image: "ghcr.io/kronbars-esports/tournaments-discord:latest"
  ds_service_name: "DS"
  ds_port: "5002"
  ds_discord_token: "{{discord_token}}"
  ds_client_id: "{{discord_client_id}}"
  ds_guild_id: "{{discord_guild_id}}"
  ds_redis_user: "{{redis_user}}"
  ds_redis_password: "{{redis_user_password}}"
  ds_redis_host: "redis"
  ds_redis_port: "{{redis_port}}"
  ds_container_name: "discord-bot"