---
  - name: Deploy al backend
    hosts: deploy_back_al
    tasks: 
      - name: Give access to socket for install user
        file: 
          path: "/var/run/docker.sock"
          state: file 
          owner: "{{ansible_user}}"
        become: yes

      - name: Copy docker template 
        template: 
          src: "/workspace/templates/backs/al.j2"
          dest: "{{base_path}}/docker/al.yml"

      - name: Pull al backend 
        shell: "cd {{base_path}}/docker/ && docker compose -f al.yml pull"
      
      - name: Stop al backend 
        shell: "cd {{base_path}}/docker/ && docker compose -f al.yml down"

      - name: Start al backend 
        shell: |
          cd {{base_path}}/docker/ && \
          AL_POSTGRES_USER={{al_pg_user}} \
          AL_POSTGRES_PASSWORD={{al_pg_password}} \
          AL_POSTGRES_DB={{al_pg_db}} \
          AL_POSTGRES_PORT={{al_pg_port}} \
          AL_POSTGRES_HOST={{al_pg_host}} \
          docker compose -f al.yml up -d